title: Lighthouse Playbook
description: This is the Lighthouse Playbook
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Monday.com: https://kpmgnz.monday.com/
  DevOps: https://kpmg-nz.visualstudio.com/
